config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :reservations
  resources :books
  resources :genres
  resources :authors
  resources :clients
  resources :librarians
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:description)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.description %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>